version: '3.1'

services:
  mongo:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./data:/tmp/data